/* Kernel Class Header File
 * 161-Ultima 2.0
 *
 * Seeing a need to coordinate resources between classes in a
 * "behind-the-scenes" way, this Kernel class was born.
 *
 * Hunter Poole
 * 04-05-2026
 */

#pragma once

#include "Sched.h"
#include "Sema.h"
#include "Uthread.h"

class Kernel {
private:
  static inline Kernel *KernelPtr = nullptr;
  Scheduler *scheduler;

  // Constructor.
  Kernel();

  // Use default destructor generated by compiler.
  ~Kernel() = default;

public:
  // Delete the copy constructor.
  Kernel(const Kernel &) = delete;

  // Delete the assignment operator.
  Kernel &operator=(const Kernel &) = delete;

  static Kernel *GetInstance();

  int CreateTask(uthread_t newthread, void *(*start_routine)(void *),
                 void *arg);

  int JoinTask(uthread_t th, void **thread_return);
};
