/* Kernel Class Header File
 * 161-Ultima 2.0
 *
 * Seeing a need to coordinate resources between classes in a
 * "behind-the-scenes" way, this Kernel class was born.
 *
 * Hunter Poole
 * 04-05-2026
 */

#pragma once

#include "Sched.h"
#include "Sema.h"
#include "Uthread.h"
#include <pthread.h>

class Kernel {
private:
  static inline Kernel *KernelPtr = nullptr;
  Scheduler *scheduler;
  vector<Semaphore *> Sema_Vector;

  // Constructor.
  Kernel();

  // Use default destructor generated by compiler.
  ~Kernel() = default;

  static void *Bootstrap_Wrapper(void *context);

  void Bootstrap(void *context);

public:
  static inline pthread_mutex_t CPULocker = PTHREAD_MUTEX_INITIALIZER;
  // Delete the copy constructor.
  Kernel(const Kernel &) = delete;

  // Delete the assignment operator.
  Kernel &operator=(const Kernel &) = delete;

  static Kernel *Get_Instance();

  int Create_Task(uthread_t newthread, void *(*start_routine)(void *),
                  void *arg);

  int Join_Task(uthread_t th, void **thread_return);

  Semaphore *Create_Semaphore(const char *name);
};

struct Context {
  Kernel *kernel;
  int task_id;
  void *(*start_routine)(void *);
  void *arg;
};
